### ISSUE TITLE
MolDepictor repo not available

### ISSUE THREAD

**Issue by hanzlika** [DS4SD/MolGrapher#1]
The proposed repo at https://github.com/DS4SD/MolDepictor/ is not publicly available. 

Without its installation, the run.sh script fails with:

Traceback (most recent call last):
  File "/home/hanzlika/Desktop/MolGrapher/molgrapher/scripts/annotate/predict_molgrapher.py", line 19, in <module>
    from molgrapher.models.graph_recognizer import GraphRecognizer
  File "/home/hanzlika/Desktop/MolGrapher/molgrapher/models/graph_recognizer.py", line 15, in <module>
    from molgrapher.models.keypoint_detector import KeypointDetector
  File "/home/hanzlika/Desktop/MolGrapher/molgrapher/models/keypoint_detector.py", line 13, in <module>
    from molgrapher.utils.utils_dataset import get_bond_size
  File "/home/hanzlika/Desktop/MolGrapher/molgrapher/utils/utils_dataset.py", line 19, in <module>
    from mol_depict.utils.utils_image import resize_image
ModuleNotFoundError: No module named 'mol_depict'

Is it possible that MolDepictor is still private?

**Comment by lucas-morin** [comment]
Hello! 
Yes, it was still private. Now, you should be able to access it: https://github.com/DS4SD/MolDepictor/

Best,
Lucas
