### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading file data/2: invalid header or archive is corrupted

### ISSUE THREAD

**Issue by Rom4e6** [DS4SD/MolGrapher#2]
Hi, dear developers!

Thank you very much for code sharing!
Following step-by-step instruction from you readme file tend me to the following issue :

```
Caption Removal Preprocessing completed in 6.79
Lightning automatically upgraded your loaded checkpoint from v1.8.1 to v2.0.9.post0. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file molgrapher/data/kd_model.ckpt`
/public/home/rom4eg/MolGrapher-main/molgrapher/data/gc_no_stereo_model.ckpt
/public/home/rom4eg/MolGrapher-main/molgrapher/data/kd_model.ckpt
Traceback (most recent call last):
  File "/public/home/rom4eg/MolGrapher-main/molgrapher/scripts/annotate/predict_molgrapher.py", line 327, in <module>
    main()
  File "/public/home/rom4eg/MolGrapher-main/molgrapher/scripts/annotate/predict_molgrapher.py", line 323, in main
    proceed_batch(args, _batch_images_paths)
  File "/public/home/rom4eg/MolGrapher-main/molgrapher/scripts/annotate/predict_molgrapher.py", line 90, in proceed_batch
    model = GraphRecognizer(
  File "/public/home/rom4eg/MolGrapher-main/molgrapher/models/graph_recognizer.py", line 53, in __init__
    self.graph_classifier = GraphClassifier.load_from_checkpoint(
  File "/public/home/rom4eg/anaconda3/envs/molgrapher/lib/python3.9/site-packages/pytorch_lightning/core/module.py", line 1543, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "/public/home/rom4eg/anaconda3/envs/molgrapher/lib/python3.9/site-packages/pytorch_lightning/core/saving.py", line 63, in _load_from_checkpoint
    checkpoint = pl_load(checkpoint_path, map_location=map_location)
  File "/public/home/rom4eg/anaconda3/envs/molgrapher/lib/python3.9/site-packages/lightning_fabric/utilities/cloud_io.py", line 52, in _load
    return torch.load(f, map_location=map_location)  # type: ignore[arg-type]
  File "/public/home/rom4eg/anaconda3/envs/molgrapher/lib/python3.9/site-packages/torch/serialization.py", line 1014, in load
    return _load(opened_zipfile,
  File "/public/home/rom4eg/anaconda3/envs/molgrapher/lib/python3.9/site-packages/torch/serialization.py", line 1422, in _load
    result = unpickler.load()
  File "/public/home/rom4eg/anaconda3/envs/molgrapher/lib/python3.9/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/public/home/rom4eg/anaconda3/envs/molgrapher/lib/python3.9/pickle.py", line 1253, in load_binpersid
    self.append(self.persistent_load(pid))
  File "/public/home/rom4eg/anaconda3/envs/molgrapher/lib/python3.9/site-packages/torch/serialization.py", line 1392, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/public/home/rom4eg/anaconda3/envs/molgrapher/lib/python3.9/site-packages/torch/serialization.py", line 1357, in load_tensor
    storage = zip_file.get_storage_from_record(name, numel, torch.UntypedStorage)._typed_storage()._untyped_storage
RuntimeError: PytorchStreamReader failed reading file data/2: invalid header or archive is corrupted
```
All libraries were installed according to your requirements in auto mode, however it installed torch 2.1.0 : 

```
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
_libgcc_mutex=0.1=conda_forge
_openmp_mutex=4.5=2_gnu
absl-py=2.0.0=pypi_0
aiohttp=3.8.6=pypi_0
aiosignal=1.3.1=pypi_0
albumentations=1.3.1=pypi_0
anyio=4.0.0=pypi_0
argon2-cffi=23.1.0=pypi_0
argon2-cffi-bindings=21.2.0=pypi_0
arrow=1.3.0=pypi_0
astor=0.8.1=pypi_0
asttokens=2.4.0=pypi_0
async-lru=2.0.4=pypi_0
async-timeout=4.0.3=pypi_0
attrdict=2.0.1=pypi_0
attrs=23.1.0=pypi_0
babel=2.13.0=pypi_0
backcall=0.2.0=pypi_0
bce-python-sdk=0.8.90=pypi_0
beautifulsoup4=4.12.2=pypi_0
bleach=6.1.0=pypi_0
blinker=1.6.3=pypi_0
bzip2=1.0.8=h7f98852_4
ca-certificates=2023.08.22=h06a4308_0
cachetools=5.3.1=pypi_0
cairo=1.16.0=hb05425b_5
cairocffi=1.6.1=pypi_0
cairosvg=2.7.1=pypi_0
certifi=2023.7.22=pypi_0
cffi=1.16.0=pypi_0
charset-normalizer=3.3.0=pypi_0
click=8.1.7=pypi_0
comm=0.1.4=pypi_0
contourpy=1.1.1=pypi_0
cssselect=1.2.0=pypi_0
cssselect2=0.7.0=pypi_0
cssutils=2.7.1=pypi_0
cycler=0.12.1=pypi_0
cython=3.0.3=pypi_0
debugpy=1.8.0=pypi_0
decorator=5.1.1=pypi_0
defusedxml=0.7.1=pypi_0
et-xmlfile=1.1.0=pypi_0
exceptiongroup=1.1.3=pypi_0
executing=2.0.0=pypi_0
fastjsonschema=2.18.1=pypi_0
fastprogress=1.0.3=pypi_0
filelock=3.12.4=pypi_0
fire=0.5.0=pypi_0
flask=3.0.0=pypi_0
flask-babel=4.0.0=pypi_0
fontconfig=2.14.1=hef1e5e3_0
fonttools=4.43.1=pypi_0
fqdn=1.5.1=pypi_0
freetype=2.12.1=h4a9f257_0
frozenlist=1.4.0=pypi_0
fsspec=2023.9.2=pypi_0
future=0.18.3=pypi_0
gensim=4.3.2=pypi_0
glib=2.69.1=he621ea3_2
graph-recognition=0.0.1=dev_0
h11=0.14.0=pypi_0
httpcore=0.18.0=pypi_0
httpx=0.25.0=pypi_0
huggingface-hub=0.17.3=pypi_0
icu=58.2=he6710b0_3
idna=3.4=pypi_0
imageio=2.31.5=pypi_0
imgaug=0.4.0=pypi_0
importlib-metadata=6.8.0=pypi_0
importlib-resources=6.1.0=pypi_0
ipykernel=6.25.2=pypi_0
ipython=8.16.1=pypi_0
isoduration=20.11.0=pypi_0
itsdangerous=2.1.2=pypi_0
jedi=0.19.1=pypi_0
jinja2=3.1.2=pypi_0
joblib=1.3.2=pypi_0
json5=0.9.14=pypi_0
jsonpointer=2.4=pypi_0
jsonschema=4.19.1=pypi_0
jsonschema-specifications=2023.7.1=pypi_0
jupyter-client=8.3.1=pypi_0
jupyter-core=5.3.2=pypi_0
jupyter-events=0.7.0=pypi_0
jupyter-lsp=2.2.0=pypi_0
jupyter-server=2.7.3=pypi_0
jupyter-server-terminals=0.4.4=pypi_0
jupyterlab=4.0.6=pypi_0
jupyterlab-pygments=0.2.2=pypi_0
jupyterlab-server=2.25.0=pypi_0
kiwisolver=1.4.5=pypi_0
lazy-loader=0.3=pypi_0
ld_impl_linux-64=2.40=h41732ed_0
levenshtein=0.22.0=pypi_0
libffi=3.4.2=h7f98852_5
libgcc-ng=13.2.0=h807b86a_2
libgomp=13.2.0=h807b86a_2
libnsl=2.0.0=hd590300_1
libpng=1.6.39=h5eee18b_0
libsqlite=3.43.0=h2797004_0
libstdcxx-ng=11.2.0=h1234567_1
libuuid=2.38.1=h0b41bf4_0
libxcb=1.15=h7f8727e_0
libxml2=2.9.14=h74e7548_0
libzlib=1.2.13=hd590300_5
lightning-utilities=0.9.0=pypi_0
lmdb=1.4.1=pypi_0
lxml=4.9.3=pypi_0
mahotas=1.4.13=pypi_0
markupsafe=2.1.3=pypi_0
matplotlib=3.8.0=pypi_0
matplotlib-inline=0.1.6=pypi_0
mistune=3.0.2=pypi_0
molecule-depictor=0.0.1=dev_0
more-itertools=10.1.0=pypi_0
mpmath=1.3.0=pypi_0
multidict=6.0.4=pypi_0
nbclient=0.8.0=pypi_0
nbconvert=7.9.2=pypi_0
nbformat=5.9.2=pypi_0
ncurses=6.4=hcb278e6_0
nest-asyncio=1.5.8=pypi_0
networkx=3.1=pypi_0
nltk=3.8.1=pypi_0
notebook-shim=0.2.3=pypi_0
numpy=1.26.0=pypi_0
nvidia-cublas-cu12=12.1.3.1=pypi_0
nvidia-cuda-cupti-cu12=12.1.105=pypi_0
nvidia-cuda-nvrtc-cu12=12.1.105=pypi_0
nvidia-cuda-runtime-cu12=12.1.105=pypi_0
nvidia-cudnn-cu12=8.9.2.26=pypi_0
nvidia-cufft-cu12=11.0.2.54=pypi_0
nvidia-curand-cu12=10.3.2.106=pypi_0
nvidia-cusolver-cu12=11.4.5.107=pypi_0
nvidia-cusparse-cu12=12.1.0.106=pypi_0
nvidia-nccl-cu12=2.18.1=pypi_0
nvidia-nvjitlink-cu12=12.2.140=pypi_0
nvidia-nvtx-cu12=12.1.105=pypi_0
opencv-contrib-python=4.6.0.66=pypi_0
opencv-python=4.6.0.66=pypi_0
opencv-python-headless=4.8.1.78=pypi_0
openpyxl=3.1.2=pypi_0
openssl=3.1.3=hd590300_0
opt-einsum=3.3.0=pypi_0
overrides=7.4.0=pypi_0
packaging=23.2=pypi_0
paddle-bfloat=0.1.7=pypi_0
paddleocr=2.7.0.3=pypi_0
paddlepaddle=2.5.1=pypi_0
pandas=2.1.1=pypi_0
pandocfilters=1.5.0=pypi_0
parso=0.8.3=pypi_0
pcre=8.45=h295c915_0
pdf2docx=0.5.6=pypi_0
pexpect=4.8.0=pypi_0
pickleshare=0.7.5=pypi_0
pillow=10.0.1=pypi_0
pip=23.2.1=pyhd8ed1ab_0
pixman=0.40.0=h7f8727e_1
platformdirs=3.11.0=pypi_0
premailer=3.10.0=pypi_0
prometheus-client=0.17.1=pypi_0
prompt-toolkit=3.0.39=pypi_0
protobuf=4.24.4=pypi_0
psutil=5.9.5=pypi_0
ptyprocess=0.7.0=pypi_0
pure-eval=0.2.2=pypi_0
pyclipper=1.3.0.post5=pypi_0
pycparser=2.21=pypi_0
pycryptodome=3.19.0=pypi_0
pygments=2.16.1=pypi_0
pymupdf=1.20.2=pypi_0
pyparsing=3.1.1=pypi_0
pytesseract=0.3.10=pypi_0
python=3.9.18=h0755675_0_cpython
python-dateutil=2.8.2=pypi_0
python-docx=0.8.11=pypi_0
python-json-logger=2.0.7=pypi_0
python-levenshtein=0.22.0=pypi_0
pytorch-lightning=2.0.9.post0=pypi_0
pytz=2023.3.post1=pypi_0
pyyaml=6.0.1=pypi_0
pyzmq=25.1.1=pypi_0
qudida=0.0.4=pypi_0
rapidfuzz=3.4.0=pypi_0
rarfile=4.1=pypi_0
rdkit-pypi=2022.9.5=pypi_0
readline=8.2=h8228510_1
referencing=0.30.2=pypi_0
regex=2023.10.3=pypi_0
requests=2.31.0=pypi_0
rfc3339-validator=0.1.4=pypi_0
rfc3986-validator=0.1.1=pypi_0
rouge-score=0.1.2=pypi_0
rpds-py=0.10.4=pypi_0
safetensors=0.4.0=pypi_0
scikit-image=0.22.0=pypi_0
scikit-learn=1.3.1=pypi_0
scipy=1.11.3=pypi_0
seaborn=0.13.0=pypi_0
send2trash=1.8.2=pypi_0
setuptools=68.2.2=pyhd8ed1ab_0
shapely=2.0.1=pypi_0
six=1.16.0=pypi_0
smart-open=6.4.0=pypi_0
smilespe=0.0.3=pypi_0
sniffio=1.3.0=pypi_0
soupsieve=2.5=pypi_0
stack-data=0.6.3=pypi_0
sympy=1.12=pypi_0
termcolor=2.3.0=pypi_0
terminado=0.17.1=pypi_0
threadpoolctl=3.2.0=pypi_0
tifffile=2023.9.26=pypi_0
timm=0.9.7=pypi_0
tinycss2=1.2.1=pypi_0
tk=8.6.13=h2797004_0
tomli=2.0.1=pypi_0
torch=2.1.0=pypi_0
torch-geometric=2.3.1=pypi_0
torchmetrics=1.2.0=pypi_0
torchsummary=1.5.1=pypi_0
torchvision=0.16.0=pypi_0
tornado=6.3.3=pypi_0
tqdm=4.66.1=pypi_0
traitlets=5.11.2=pypi_0
triton=2.1.0=pypi_0
types-python-dateutil=2.8.19.14=pypi_0
typing-extensions=4.8.0=pypi_0
tzdata=2023.3=pypi_0
uri-template=1.3.0=pypi_0
urllib3=2.0.6=pypi_0
visualdl=2.5.3=pypi_0
wcwidth=0.2.8=pypi_0
webcolors=1.13=pypi_0
webencodings=0.5.1=pypi_0
websocket-client=1.6.4=pypi_0
weighted-levenshtein=0.2.2=pypi_0
werkzeug=3.0.0=pypi_0
wheel=0.41.2=pyhd8ed1ab_0
xz=5.2.6=h166bdaf_0
yarl=1.9.2=pypi_0
zipp=3.17.0=pypi_0
zlib=1.2.13=hd590300_5
```
The models were downloaded directly from HF

**Comment by lucas-morin** [comment]
Hello,

How did you download the models on Hugging Face? 
Do you have `Git LFS` correctly installed?

Best, 
Lucas

**Comment by Rom4e6** [comment]
> Hello,
> 
> How did you download the models on Hugging Face? Do you have `Git LFS` correctly installed?
> 
> Best, Lucas

Hi, Lucas!

Thanks for your reply!

I downloaded it manually via browser's at HF link 
Does it play role? 


Best,
Roman

**Comment by lucas-morin** [comment]
Hi! 
Ok, then it should be good. 
Are you able to run the following?

```
(molgrapher) $ python3
>>> import torch
>>> checkpoint = torch.load('gc_no_stereo_model.ckpt', map_location=torch.device('cpu'))
```

Best,
Lucas

**Comment by lucas-morin** [comment]
I am closing this issue since there is no activity.
